package com.example.bugtest.controller;

import com.example.bugtest.model.Order;
import com.example.bugtest.model.OrderItem;
import com.example.bugtest.service.InventoryService;
import com.example.bugtest.service.OrderService;
import com.example.bugtest.service.ReportService;
import com.example.bugtest.util.DateUtils;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api")
public class OrderController {

    private final OrderService orderService;
    private final InventoryService inventoryService;
    private final ReportService reportService;

    public OrderController(OrderService orderService,
                           InventoryService inventoryService,
                           ReportService reportService) {
        this.orderService = orderService;
        this.inventoryService = inventoryService;
        this.reportService = reportService;
    }

    @PostMapping("/orders")
    public Order createOrder(@RequestBody OrderRequest request) {
        return orderService.createOrder(request.getCustomerName(), request.getItems());
    }

    @GetMapping("/orders")
    public List<Order> listOrders(@RequestParam(defaultValue = "1") int page,
                                  @RequestParam(defaultValue = "10") int size) {
        return orderService.listOrders(page, size);
    }

    @GetMapping("/orders/{id}")
    public Order getOrder(@PathVariable Long id) {
        return orderService.getOrder(id);
    }

    @PostMapping("/orders/{id}/pay")
    public Map<String, Object> payOrder(@PathVariable Long id) {
        // payOrder now returns the updated order — no second repository lookup,
        // and a not-yet-paid order no longer causes an NPE on getPaidAt()
        Order order = orderService.payOrder(id);
        Map<String, Object> result = new HashMap<>();
        result.put("id", id);
        result.put("status", order.getStatus());
        result.put("paidAt", order.getPaidAt() == null
                ? null
                : DateUtils.format(order.getPaidAt()));
        return result;
    }

    @PostMapping("/orders/{id}/cancel")
    public void cancelOrder(@PathVariable Long id) {
        orderService.cancelOrder(id);
    }

    @PostMapping("/orders/{id}/refund")
    public void refundOrder(@PathVariable Long id) {
        orderService.refundOrder(id);
    }

    @PostMapping("/orders/{id}/export")
    public Map<String, Object> exportOrder(@PathVariable Long id) {
        // The export path is now generated by the service under a fixed directory.
        // The client no longer controls the path (fixes arbitrary file write).
        Order order = orderService.getOrder(id);
        String path = reportService.exportOrder(order);
        Map<String, Object> result = new HashMap<>();
        result.put("exported", path);
        return result;
    }

    /**
     * Bulk import product names from a dot-separated string, e.g. "apple.banana.orange".
     */
    @PostMapping("/products/import")
    public List<String> importProducts(@RequestParam String names) {
        if (names == null || names.isBlank()) {
            return Collections.emptyList();
        }
        // '.' is a regex metacharacter, it must be escaped
        String[] parts = names.split("\\.");
        List<String> imported = new ArrayList<>();
        for (String part : parts) {
            String trimmed = part.trim();
            if (!trimmed.isEmpty()) {
                imported.add(trimmed);
            }
        }
        return imported;
    }

    @GetMapping("/inventory/{sku}")
    public Map<String, Object> getStock(@PathVariable String sku) {
        Map<String, Object> result = new HashMap<>();
        result.put("sku", sku);
        result.put("stock", inventoryService.getStock(sku));
        return result;
    }

    public static class OrderRequest {
        private String customerName;
        private List<OrderItem> items;

        public String getCustomerName() {
            return customerName;
        }

        public void setCustomerName(String customerName) {
            this.customerName = customerName;
        }

        public List<OrderItem> getItems() {
            return items;
        }

        public void setItems(List<OrderItem> items) {
            this.items = items;
        }
    }
}
